// components/header/Header.tsx
"use client";
// import useMounted from "@/hooks/useMounted";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { twMerge } from "tailwind-merge";
import Menu from "../Menu";
import { Button } from "../ui/button";

const Header = () => {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [isScrolled, setIsScrolled] = useState(() => {
    // Initialize based on current scroll position
    return typeof window !== "undefined" ? window.scrollY > 0 : false;
  });
  const ICON_SIZE = 24;
  const pathname = usePathname();
  // const isMounted = useMounted();

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 0) {
        setIsScrolled(true);
      } else {
        setIsScrolled(false);
      }
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setIsDrawerOpen(false);
  }, [pathname]);

  useEffect(() => {
    if (isDrawerOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "auto";
    }
  }, [isDrawerOpen]);

  const buttonBaseClasses = twMerge(
    "text-xs md:text-sm tracking-wide transition-all duration-100 ease-in-out",
  );

  return (
    <>
      <div
        className={twMerge(
          "fixed top-0 md:top-4 left-0 right-0 w-full md:w-fit z-9999 transition-all duration-100 ease-in-out mx-auto flex flex-col items-center",
        )}
      >
        <header
          className={twMerge(
            "md:rounded-full backdrop-blur-sm border-b md:border w-full md:w-fit md:max-w-[700px] border-border/50",
            isDrawerOpen ? "bg-background" : "bg-background/75",
          )}
        >
          <div className={twMerge("px-4 py-2.5 md:px-8 flex md:justify-center")}>
            <div className={twMerge("flex items-center w-full justify-between")}>
              <Link
                href="/"
                className={twMerge(
                  "h-auto w-24 transition-all duration-300 ease-in-out opacity-50 hover:opacity-100",
                  isScrolled ? "md:mr-4" : "md:mr-24",
                  isDrawerOpen && "md:mr-48",
                )}
              >
                <Image
                  priority
                  quality={100}
                  fill
                  alt="Logo"
                  src="/logo.png"
                  className="relative! transition-all duration-100 ease-in-out"
                />
              </Link>

              <div className="flex items-center gap-2">
                <Link href="/tjanster" className={twMerge(buttonBaseClasses, "hidden sm:block")}>
                  <Button variant="ghost">Tjänster</Button>
                </Link>
                <Link
                  href="/case"
                  className={twMerge(buttonBaseClasses, "hidden sm:block md:hidden lg:block")}
                >
                  <Button variant="ghost">Case</Button>
                </Link>
                <Link
                  href="/case"
                  className={twMerge(buttonBaseClasses, "hidden sm:block md:hidden lg:block")}
                >
                  <Button variant="ghost">Kontakt</Button>
                </Link>
                <Menu isOpen={isDrawerOpen} setIsOpen={setIsDrawerOpen} />
              </div>
            </div>
          </div>
        </header>
      </div>
    </>
  );
};

export default Header;

// src/lib/components/Header.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import Drawer from '$lib/components/drawer/Drawer.svelte';
	import { onDestroy, onMount } from 'svelte';
	let isOpen: boolean = false;
	const handleToggle = () => {
		isOpen = !isOpen;
	};
	let y = 0;
	$: isScroll = y > 0;
	$: isScrollClasses =
		isScroll || isOpen ? 'bg-[#ece9ff] backdrop-blur-md bg-opacity-80' : 'bg-transparent';
	$: innerWidth = 0;
	$: smScreen = innerWidth < 768;
	$: $page.route.id, (isOpen = false);
	let mounted = false;
	onMount(() => {
		setTimeout(() => {
			mounted = true;
		}, 1000);
	});
	onDestroy(() => {
		mounted = false;
	});
</script>

<header
	class="duration-500 transition-all ease-in-out {mounted
		? 'translate-y-0 opacity-100'
		: '-translate-y-12 opacity-0'}"
>
	<nav class={isScrollClasses}>
		<a href="/" on:click={() => (isOpen = false)}>
			<img src="/images/appstract_logo_black.png" alt="Appstract" />
			<h2>Appstract</h2>
		</a>
		<button on:click={handleToggle}>
			{isOpen ? 'Stäng' : 'Meny'}
		</button>
	</nav>
</header>
<Drawer {isOpen} on:clickAway={handleToggle} on:closeButton={handleToggle} />
<svelte:window bind:innerWidth bind:scrollY={y} />

<style lang="scss">
	img {
		@apply w-8 md:w-12 h-full;
	}
	a {
		@apply flex items-center gap-4;
	}
	header {
		@apply transition-all duration-1000 z-[999] left-0 right-0 fixed top-0 p-0 xl:py-4 md:py-2 md:px-2 max-w-[1328px] mx-auto;
	}
	nav {
		@apply flex items-center justify-between md:rounded px-4 transition-all duration-200 py-4;
	}
	h2 {
		@apply text-lg md:text-xl lowercase font-bold text-[#292929];
		font-family: var(--font-varela);
	}
	button {
		@apply hover:underline-offset-4 hover:underline uppercase text-base transition-all duration-200 ease-in-out text-[#292929];
		font-family: var(--font-varela);
	}
</style>
